openapi: 3.0.0
info:
  title: ONDC Specification
  domain: ONDC:FIS13
  description: ONDC Specification
  version: 2.0.0
  x-usecases:
    - HEALTH INSURANCE
    - MOTOR INSURANCE
    - ACCIDENTAL INSURANCE
    - HOSPICASH INSURANCE
    - TRANSIT INSURANCE
  x-branch-name: draft-FIS13-HEALTH-2.0.0
  x-reporting: true
security:
  - SubscriberAuth: []
paths:
  $ref: ./specs/openapi.yaml#/paths
components:
  $ref: ./specs/openapi.yaml#/components
x-attributes:
  $ref: ./attributes/index.yaml
x-validations:
  $ref: ./validations/index.yaml
x-errorcodes:
  $ref: ./errors/index.yaml
x-supported-actions:
  $ref: ./actions/index.yaml
x-flows:
  $ref: ./flows/index.yaml#/flows
x-docs:
  $ref: ./docs
